version: '3.8'
services:
  database:
    image: postgres
    ports:
      - 6000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ft_transcendence
      POSTGRES_PASSWORD: 123
    networks:
      - peterPan

networks:
  peterPan: