version: '3.8'
services:
  database:
    image: postgres
    env_file:
      - ./backend/.env
    ports:
      - "7001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ft_transcendence
      POSTGRES_PASSWORD: 123
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
networks:
  peterPan: