version: '3.8'
services:
  database:
    image: postgres
    env_file:
      - ./backend/.env
    ports:
      - "${PORT_DB}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ft_transcendence
      POSTGRES_PASSWORD: 123
networks:
  peterPan: