version: '3'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT_DB=${PORT_DB}
      - HOSTNAME=${HOSTNAME}
    networks:
      frontend_network:
        aliases:
          - frontend
    volumes:
      - frontend:/app

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - database
    env_file:
      - ./.env
    networks:
      frontend_network:
        aliases:
          - backend
      backend_network:
        aliases:
          - backend
    volumes:
      - backend:/app

  database:
    image: postgres
    ports:
      - ${PORT_DB}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      backend_network:
        aliases:
          - db

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  backend:
    driver: local
    driver_opts:
      type: none
      device: backend
      o: bind
  frontend:
    driver: local
    driver_opts:
      type: none
      device: frontend
      o: bind
